--=====================================================================
--  MythicHandHolding — Raid content (alpha, issue #2)
--  Midnight Season 2 (12.1): The Venomous Abyss, The Tidebound Grotto.
--  Midnight Season 1: Voidspire, Dreamrift, March on Quel'Danas, Sporefall (12.0.7).
--
--  Fill IDs from Adventure Guide (no need to be inside the raid):
--    /mhh ej list              — list raid instances + EJ IDs
--    /mhh ej <name or id>      — boss encounter IDs for that raid
--    /mhh ej spells <boss|id>  — ability/spell IDs for one boss
--    /mhh ej diff <14|15|16|17>— journal difficulty for dumps (N/H/M/LFR)
--
--  Section optional field:
--    extraByDiff = { [15] = { "Heroic-only tip" }, [16] = { "Mythic-only tip" } }
--  Journal difficulty IDs: 17=LFR, 14=Normal, 15=Heroic, 16=Mythic.
--=====================================================================

MHH_Raids = {
  journalDiff = 14,  -- default Normal raid journal links (dungeons use 23)

  -- Encounter IDs from Adventure Guide (/mhh ej) — 2026-07-03.
  -- EJ instance IDs: Voidspire 1307, Dreamrift 1314, Quel'Danas 1308,
  -- Sporefall 1305, Midnight world bosses 1312.
  bossIds = {
    -- Season 2 (12.1): The Venomous Abyss (EJ instance 1320)
    ["Nek'zali the Soulcoiler"]       = 2888,
    ["Nek'zali"]                       = 2888,
    ["Entombed Sentinels"]            = 2874,
    ["The Lost Explorers"]            = 2894,
    ["Vashnik the Malignant"]         = 2882,
    ["Vashnik"]                        = 2882,
    ["Sszorak"]                        = 2871,
    ["The Twin Fangs"]                = 2887,
    ["The Coiled Altar"]              = 2883,
    ["Ula'tek"]                        = 2895,
    -- Season 2 (12.1): The Tidebound Grotto lair (EJ instance 1317)
    ["Nymrissa Wavecaller"]           = 2849,
    ["Nymrissa"]                       = 2849,
    -- Season 1
    ["Imperator Averzian"]            = 2733,
    ["Vorasius"]                       = 2734,
    ["Fallen-King Salhadaar"]          = 2736,
    ["Vaelgor & Ezzorak"]             = 2735,
    ["Vaelgor"]                        = 2735,
    ["Ezzorak"]                        = 2735,
    ["Lightblinded Vanguard"]         = 2737,
    ["Crown of the Cosmos"]           = 2738,
    ["Alleria Windrunner"]            = 2738,
    ["Chimaerus the Undreamt God"]    = 2795,
    ["Chimaerus, the Undreamt God"]   = 2795,
    ["Chimaerus"]                      = 2795,
    ["Belo'ren, Child of Al'ar"]       = 2739,
    ["Belo'ren"]                       = 2739,
    ["Midnight Falls"]                 = 2740,
    ["L'ura"]                          = 2740,
    ["Rotmire"]                        = 2711,
    -- Outdoor world bosses (EJ "Midnight" instance 1312)
    ["Lu'ashal"]                       = 2827,
    ["Thorm'belan"]                    = 2829,
    ["Predaxas"]                       = 2828,
    ["Cragpine"]                       = 2782,
  },

  -- Optional: pin EJ instance IDs for /mhh ej name matching.
  instanceIds = {
    ["The Venomous Abyss"]    = 1320,
    ["The Tidebound Grotto"]  = 1317,
    ["The Voidspire"]         = 1307,
    ["The Dreamrift"]         = 1314,
    ["March on Quel'Danas"]   = 1308,
    ["Sporefall"]             = 1305,
    ["Midnight"]              = 1312,  -- world bosses
  },

  -- Full Adventure Guide dump (Normal). Duplicate names keep the first ID.
  -- Only names that appear in tip text are hyperlinked (see RebuildRaidSpellLinkable).
  spellIds = {
    -- Imperator Averzian
    ["Black Miasma"] = 1275059,
    ["Blackening Wounds"] = 1265540,
    ["Cosmic Shell"] = 1280035,
    ["Dark Barrage"] = 1274846,
    ["Dark Resilience"] = 1264164,
    ["Dark Upheaval"] = 1249251,
    ["Gathering Darkness"] = 1255749,
    ["Gnashing Void"] = 1255683,
    ["Hobbled"] = 1267205,
    ["Imperator's Glory"] = 1253918,
    ["Lingering Darkness"] = 1280075,
    ["March of the Endless"] = 1251583,
    ["Oblivion's Wrath"] = 1260712,
    ["Pitch Bulwark"] = 1255702,
    ["Shadow Phalanx"] = 1284786,
    ["Shadow's Advance"] = 1251361,
    ["Umbral Barrier"] = 1249714,
    ["Umbral Collapse"] = 1249262,
    ["Void Fall"] = 1258883,
    ["Void Marked"] = 1280015,
    ["Void Rupture"] = 1262036,
    ["Weakened"] = 1283069,
    -- Vorasius
    ["Aftershock"] = 1273067,
    ["Blisterburst"] = 1259186,
    ["Creep Spit"] = 1272527,
    ["Dark Energy"] = 1280101,
    ["Dark Goo"] = 1243270,
    ["Overpowering Pulse"] = 1244419,
    ["Parasite Expulsion"] = 1254199,
    ["Primordial Power"] = 1272937,
    ["Primordial Roar"] = 1260052,
    ["Shadowclaw Slam"] = 1241692,
    ["Smashed"] = 1241844,
    ["Void Breath"] = 1256855,
    -- Fallen-King Salhadaar
    ["Dark Radiation"] = 1250991,
    ["Despotic Command"] = 1248697,
    ["Destabilizing Strikes"] = 1271577,
    ["Entropic Unraveling"] = 1246175,
    ["Fractured Projection"] = 1254081,
    ["Nexus Shield"] = 1275056,
    ["Oppressive Darkness"] = 1248709,
    ["Shadow Fracture"] = 1254088,
    ["Shattering Twilight"] = 1253032,
    ["Torturous Extract"] = 1245592,
    ["Twilight Spikes"] = 1251213,
    ["Twisting Obscurity"] = 1250686,
    ["Umbral Beams"] = 1260015,
    ["Void Convergence"] = 1247738,
    ["Void Exposure"] = 1250828,
    ["Void Infusion"] = 1245960,
    -- Vaelgor & Ezzorak
    ["Aura of Light"] = 1272867,
    ["Cosmosis"] = 1263623,
    ["Diminish"] = 1270852,
    ["Dread Breath"] = 1244221,
    ["Gloom"] = 1245391,
    ["Gloomfield"] = 1245420,
    ["Gloomtouched"] = 1245554,
    ["Grappling Maw"] = 1280458,
    ["Impale"] = 1265152,
    ["Midnight Flames"] = 1249748,
    ["Midnight Manifestation"] = 1255763,
    ["Nullbeam"] = 1262623,
    ["Nullscatter"] = 1266570,
    ["Nullsnap"] = 1244413,
    ["Nullzone"] = 1244672,
    ["Nullzone Implosion"] = 1252157,
    ["Radiant Barrier"] = 1248847,
    ["Rakfang"] = 1245645,
    ["Shadowmark"] = 1270513,
    ["Tail Lash"] = 1264467,
    ["Twilight Bond"] = 1270189,
    ["Twilight Fury"] = 1270250,
    ["Unbound Shadow"] = 1251686,
    ["Vaelwing"] = 1265131,
    ["Void Howl"] = 1244917,
    ["Voidbolt"] = 1245175,
    -- Lightblinded Vanguard (raid-specific IDs; not merged into M+ SPELL_IDS)
    ["Aura of Devotion"] = 1246162,
    ["Aura of Peace"] = 1248451,
    ["Aura of Wrath"] = 1248449,
    ["Avenger's Shield"] = 1246485,
    ["Avenging Wrath"] = 1246385,
    ["Blinding Light"] = 1258514,
    ["Consecration"] = 1246155,
    ["Divine Consecration"] = 1276982,
    ["Divine Hammer"] = 1249047,
    ["Divine Shield"] = 1246384,
    ["Divine Storm"] = 1246765,
    ["Divine Tempest"] = 1272324,
    ["Divine Toll"] = 1248644,
    ["Elekk Charge"] = 1249130,
    ["Execution Sentence"] = 1280159,
    ["Exorcism"] = 1246745,
    ["Final Verdict"] = 1251812,
    ["Forbearance"] = 1246391,
    ["Judgment"] = 1251857,
    ["Light Infused"] = 1258659,
    ["Retribution"] = 1256133,
    ["Sacred Shield"] = 1248674,
    ["Sacred Toll"] = 1246749,
    ["Searing Radiance"] = 1255738,
    ["Shield of the Righteous"] = 1251859,
    ["Spirit of the Defender"] = 1272700,
    ["Spirit of the Mender"] = 1272471,
    ["Spirit of the Vindictive"] = 1272699,
    ["Tyr's Wrath"] = 1248710,
    ["Zealous Spirit"] = 1276243,
    -- Crown of the Cosmos
    ["Aspect of the End"] = 1239080,
    ["Bursting Emptiness"] = 1232784,
    ["Call of the Void"] = 1256787,
    ["Coalesced Form"] = 1238672,
    ["Corrupting Essence"] = 1261531,
    ["Cosmic Barrier"] = 1246918,
    ["Dark Hand"] = 1233787,
    ["Dark Rush"] = 1238708,
    ["Devouring Cosmos"] = 1238843,
    ["Echoing Darkness"] = 1233778,
    ["Empowering Darkness"] = 1237251,
    ["Grasp of Emptiness"] = 1232467,
    ["Gravity Collapse"] = 1239089,
    ["Interrupting Tremor"] = 1243743,
    ["Null Corona"] = 1233865,
    ["Orbiting Matter"] = 1245874,
    ["Ranger Captain's Mark"] = 1237614,
    ["Ravenous Abyss"] = 1243753,
    ["Rift Slash"] = 1246461,
    ["Silver Residue"] = 1233689,
    ["Silverstrike Arrow"] = 1233602,
    ["Silverstrike Barrage"] = 1243982,
    ["Silverstrike Ricochet"] = 1237729,
    ["Singularity Eruption"] = 1235622,
    ["Stellar Emission"] = 1234569,
    ["Umbral Tether"] = 1233470,
    ["Void Barrage"] = 1260000,
    ["Void Expulsion"] = 1255368,
    ["Void Remnants"] = 1242553,
    ["Voidstalker Sting"] = 1237038,
    ["Volatile Fissure"] = 1238206,
    -- Chimaerus
    ["Alndust Essence"] = 1245919,
    ["Alndust Upheaval"] = 1282001,
    ["Alnshroud"] = 1245727,
    ["Alnsight"] = 1245698,
    ["Cannibalized Essence"] = 1245844,
    ["Caustic Phlegm"] = 1246653,
    ["Colossal Strikes"] = 1262020,
    ["Consume"] = 1245396,
    ["Consuming Miasma"] = 1257085,
    ["Corrupted Devastation"] = 1245486,
    ["Discordant Roar"] = 1249207,
    ["Dissonance"] = 1267201,  -- Chimaerus (also on Midnight Falls)
    ["Essence Bolt"] = 1261997,
    ["Fearsome Cry"] = 1249017,
    ["Insatiable"] = 1252863,
    ["Lingering Miasma"] = 1257093,
    ["Ravenous Dive"] = 1245406,
    ["Rending Tear"] = 1272726,
    ["Rift Emergence"] = 1258610,
    ["Rift Madness"] = 1264756,
    ["Rift Shroud"] = 1246132,
    ["Rift Sickness"] = 1250953,
    ["Rift Vulnerability"] = 1253744,
    -- Belo'ren
    ["Ashen Benediction"] = 1262573,
    ["Burning Heart"] = 1283067,
    ["Death Drop"] = 1246709,
    ["Embers of Belo'ren"] = 1241282,
    ["Eternal Burns"] = 1244344,
    ["Guardian's Edict"] = 1260763,
    ["Immortal Flame"] = 1243320,
    ["Incubation of Flames"] = 1242792,
    ["Infused Quills"] = 1242260,
    ["Light Blast"] = 1264696,
    ["Light Burn"] = 1244348,
    ["Light Dive"] = 1241292,
    ["Light Echo"] = 1243021,
    ["Light Edict"] = 1261217,
    ["Light Eruption"] = 1243852,
    ["Light Feather"] = 1241162,
    ["Light Flames"] = 1242803,
    ["Light Patch"] = 1241838,
    ["Light Quill"] = 1242093,
    ["Radiant Echoes"] = 1242981,
    ["Rebirth"] = 1263412,
    ["Void Blast"] = 1264698,
    ["Void Burn"] = 1266404,
    ["Void Dive"] = 1241339,
    ["Void Echo"] = 1243026,
    ["Void Edict"] = 1261218,
    ["Void Eruption"] = 1243854,
    ["Void Feather"] = 1241163,
    ["Void Flames"] = 1242815,
    ["Void Patch"] = 1241845,
    ["Void Quill"] = 1242094,
    ["Voidlight Convergence"] = 1242515,
    ["Voidlight Edict"] = 1241640,
    ["Voidlight Rupture"] = 1243866,
    -- Midnight Falls
    ["Abyssal Pool"] = 1282008,
    ["Black Shroud"] = 1285685,
    ["Black Tide"] = 1263253,
    ["Charged Core"] = 1282373,
    ["Core Harvest"] = 1282412,
    ["Cosmic Fission"] = 1282249,
    ["Cosmic Fracture"] = 1251789,
    ["Criticality"] = 1281184,
    ["Dark Constellation"] = 1266388,
    ["Dark Meltdown"] = 1281194,
    ["Dark Quasar"] = 1279420,
    ["Dark Rune"] = 1249609,
    ["Dawnlight Barrier"] = 1253104,
    ["Death's Dirge"] = 1244412,
    ["Death's Requiem"] = 1273158,
    ["Decay"] = 1284638,
    ["Dimension Breach"] = 1276529,
    ["Dimension Link"] = 1276062,
    ["Dimming"] = 1252974,
    ["Disintegration"] = 1251649,
    ["Eclipsed"] = 1262055,
    ["Galvanize"] = 1284525,
    ["Glimmering"] = 1254398,
    ["Grim Symphony"] = 1284980,
    ["Heaven's Glaives"] = 1253915,
    ["Heaven's Lance"] = 1263970,
    ["Impaled"] = 1265842,
    ["Into the Darkwell"] = 1282034,
    ["Iris of Oblivion"] = 1279463,
    ["Light Siphon"] = 1266897,
    ["Light's End"] = 1284699,
    ["Midnight"] = 1266622,
    ["Naaru's Lament"] = 1254256,
    ["Overkill Current"] = 1285827,
    ["Radiance"] = 1282458,
    ["Resonance"] = 1249582,
    ["Safeguard"] = 1251392,
    ["Safeguard Prism"] = 1251386,
    ["Severance"] = 1274455,
    ["Severed Surge"] = 1287702,
    ["Shattered Sky"] = 1249796,
    ["Starsplinter"] = 1282441,
    ["Stellar Implosion"] = 1266898,
    ["Tears of L'ura"] = 1254262,
    ["Terminate"] = 1284934,
    ["Termination Prism"] = 1284931,
    ["The Dark Archangel"] = 1250898,
    ["The Darkwell"] = 1282027,
    ["Thunderous Well"] = 1254642,
    ["Torchbearer"] = 1266113,
    ["Total Eclipse"] = 1260261,
    ["Void Cores"] = 1282246,
    -- Rotmire / Sporefall
    ["Awaken Fungi"] = 1221622,
    ["Blightshot"] = 1221717,
    ["Bursting Doom Shroom"] = 1222495,
    ["Bursting Pustules"] = 1221787,
    ["Bursting Shroom"] = 1221965,
    ["Cross Fertilization"] = 1222684,
    ["Festering Vines"] = 1222088,
    ["Fungal Bloom"] = 1221637,
    ["Fungal Frenzy"] = 1221644,
    ["Poison Burst"] = 1221714,
    ["Putrid Fist"] = 1221781,
    ["Rotting Pustules"] = 1222176,
    ["Writhing Vines"] = 1222129,
    -- World bosses
    ["Blinding Fissure"] = 1243988,
    ["Dawncrazed Halo"] = 1276436,
    ["Dawnfire Breath"] = 1276247,
    ["Radiant Ember"] = 1258426,
    ["Radiant Flare"] = 1258427,
    ["Radiant Sunder"] = 1243963,
    ["Ancient Seeds"] = 1257906,
    ["Erupting Roots"] = 1235134,
    ["Rootquake"] = 1235131,
    ["War Club"] = 1235144,
    -- Thorm'belan
    ["Dazzling Radiance"] = 1257618,
    ["Radiant Mote"] = 1257320,
    ["Rending Claw"] = 1258136,
    ["Scintillating Shard"] = 1257825,
    ["Shard Eruption"] = 1257737,
    ["Shredding Tendrils"] = 1258639,
    -- Predaxas
    ["Bestial Rage"] = 1277711,
    ["Bilepool"] = 1277043,
    ["Blood Nova"] = 1277694,
    ["Devour"] = 1277829,
    ["Regurgitation"] = 1276193,
    ["Seismic Slam"] = 1276320,
    ["Toxin Splatter"] = 1276988,
    ["Voidscatter"] = 1276884,

    -- ============ Season 2 (12.1) ============
    -- Nek'zali the Soulcoiler
    ["Cremation"] = 1289875,
    ["Essence Rend"] = 1287426,
    ["Hungering Pyre"] = 1289855,
    ["Possession Barrage"] = 1284103,
    ["Restless Amani"] = 1289919,
    ["Soulcoil Well"] = 1285623,
    -- Entombed Sentinels
    ["Blighted Blood"] = 1284471,
    ["Helical Toxins"] = 1284590,
    ["Mark of Acid"] = 1284494,
    ["Mark of Blood"] = 1284503,
    ["Toxic Droplets"] = 1284434,
    ["Ula'tek's Dominance"] = 1290193,
    ["Unstable Miasma"] = 1288232,
    ["Venom Coagulation"] = 1284251,
    ["Vitriolic Stasis"] = 1284588,
    -- The Lost Explorers
    ["Blink Nova"] = 1296025,
    ["Final Ascension"] = 1292779,
    ["Shell Spin"] = 1296061,
    ["Throw Junk"] = 1291933,
    -- Vashnik the Malignant
    ["Exploding Infection"] = 1295173,
    ["Imbibe"] = 1283164,
    ["Malignant Catalyst"] = 1282525,
    ["Plague Froth"] = 1281907,
    ["Siphon Blood"] = 1295229,
    ["Stygian Infection"] = 1294994,
    -- Sszorak
    ["Apex Predator"] = 1277025,
    ["Dig In"] = 1286033,
    ["Howling Maelstrom"] = 1285732,
    ["Mutilate"] = 1277027,
    ["Raging Crosswinds"] = 1285419,
    ["Ravage"] = 1277002,
    ["Tempest"] = 1287072,
    ["Venomous Surge"] = 1305959,
    -- The Twin Fangs
    ["Caustic Globule"] = 1289993,
    ["Coiling Ichor"] = 1290809,
    ["Eternal Venom"] = 1290336,
    ["Ravenous Feast"] = 1290516,
    ["Stir the Depths"] = 1290956,
    ["Stone Breaker"] = 1288538,
    ["Submerge"] = 1308556,
    ["Venomous Emergence"] = 1291404,
    -- The Coiled Altar
    ["Axegrinder"] = 1301111,
    ["Coalesced Venom"] = 1282403,
    ["Dreadmarch"] = 1285643,
    ["Eternal Nightfall"] = 1286918,
    ["Ghastly Regeneration"] = 1304033,
    ["Gloombomb"] = 1310882,
    ["Guillotine"] = 1283489,
    ["Sever"] = 1299680,
    ["Soul Sever"] = 1286620,
    ["Soulbound"] = 1309987,
    ["Spiritcackle"] = 1286441,
    -- Ula'tek
    ["Anguished Cry"] = 1305650,
    ["Call of the Serpent"] = 1304012,
    ["Caustic Waves"] = 1292403,
    ["Circling Prey"] = 1301510,
    ["Doomscale Cauldron"] = 1313355,
    ["Petrifying Sting"] = 1303414,
    ["Poisonous Bite"] = 1287036,
    ["Rage of the Shackled"] = 1286860,
    ["Serpent's Bite"] = 1295905,
    ["Soul Constrictor"] = 1300685,
    ["Spectral Coils"] = 1287265,
    ["Volatile Purge"] = 1306086,
    -- Nymrissa Wavecaller (Tidebound Grotto)
    ["Chilling Frost"] = 1313393,
    ["Frost Orb"] = 1313402,
    ["Swirling Whirlpools"] = 1258668,
    ["Water Jet"] = 1258901,
  },

  -- Optional per-difficulty spell overrides (merged on top when that diff is active).
  spellIdsByDiff = {
  },

  raids = {
    ------------------------------------------------------------------
    -- The Venomous Abyss (8 bosses, patch 12.1 / Season 2)
    -- Boss 1, then two wings of two, then bosses 6-8 from the central pit.
    ------------------------------------------------------------------
    {
      name = "The Venomous Abyss",
      tab  = "TVA",
      tier = "Midnight S2 (12.1)",
      sections = {
        { label = "Interrupts/Dispels",
          title = "=== VENOMOUS ABYSS - INT/DISP ===",
          lines = {
            "INTERRUPT: Anguished Cry (Weakened Doomscale, Ula'tek P2), Spiritcackle adds (Coiled Altar Heroic)",
            "DISPEL: Essence Rend (Nek'zali — target moves to the wall FIRST, dispel drops a puddle)",
            "DISPEL: Blighted Blood (Entombed Sentinels) fast; Exploding Infection (Vashnik orange) staggered — it AoEs on removal",
            "Eternal Nightfall (Malacrass): break the shield to stop the cast — no interrupt needed",
          } },
        { label = "Nek'zali the Soulcoiler",
          boss  = "Nek'zali the Soulcoiler",
          title = "=== NEK'ZALI THE SOULCOILER ===",
          lines = {
            "Never die in the Soulcoil Well and never let Restless Amani reach it — boss empowers for the rest of the fight",
            "Essence Rend: run to the room edge, call for dispel, drop the puddle out of the way",
            "Possession Barrage: tank runs away from the boss until it impacts",
            "Intermission at 50%: melee + tanks group-soak Hungering Pyre, singles take Cremation on the leftover corpses",
            "Lust on pull",
          },
          extraByDiff = {
            [15] = { "Heroic+: add corpses only die permanently once burned by Hungering Pyre or Cremation" },
          } },
        { label = "Entombed Sentinels",
          boss  = "Entombed Sentinels",
          title = "=== ENTOMBED SENTINELS ===",
          lines = {
            "Tank the two sentinels 40y apart or Ula'tek's Dominance gives them 99% damage reduction",
            "Mark of Acid / Mark of Blood: stay 40y from the OTHER boss or you collect stacks",
            "Green (acid) side: burn Venom Coagulation slime on spawn, step on Toxic Droplets to squish them",
            "Red (blood) side: everyone soaks Unstable Miasma at an edge; dispel Blighted Blood immediately",
            "100 energy: Vitriolic Stasis wastes damage — pair Helical Toxins so your green orbs total 4",
            "After intermission tanks taunt swap and bring both bosses to the same side",
          },
          extraByDiff = {
            [15] = {
              "Heroic: after soaking Unstable Miasma, stand next to another blood player to pass the debuff",
              "Heroic: dodge the daggers the tiny slimes fire into the green boss",
            },
          } },
        { label = "The Lost Explorers",
          boss  = "The Lost Explorers",
          title = "=== THE LOST EXPLORERS ===",
          lines = {
            "Mor'zahi at 100 energy = raid wipe — feed Disgusting Fish from Trader Gebbo's crates to reset it",
            "Each tortollan can be fed ONCE — three resets total, so kill them before the fish runs out",
            "Tank two bosses together; Gebbo wanders counter-clockwise on his own",
            "Nama Shell Spin: dodge the 3 shells in the frontal cone",
            "Iku Blink Nova: drag it away from raid, in the direction you want Iku to teleport",
            "Gebbo Throw Junk: soak crates (watch bleed stacks) and find the fish",
            "Fed bosses gain extras — Nama 3 group soaks, Iku Fire/Frost circles (walk into the OPPOSITE puddle), Gebbo bomb ring (mushroom-bounce it)",
          },
          extraByDiff = {
            [15] = { "Heroic: only TWO bosses may be tanked together — all three = 99% damage reduction" },
          } },
        { label = "Vashnik the Malignant",
          boss  = "Vashnik the Malignant",
          title = "=== VASHNIK THE MALIGNANT ===",
          lines = {
            "Imbibe draws the two NEAREST fountains — tank in a different third of the room each cast to control the venoms",
            "Plague Froth: spread and stand still so everyone else can dodge the waves",
            "Purple altar: 5 slimes, AoE them, dodge the swirlies on death",
            "Orange altar: 2 slimes, CC-able 60s, stagger the kills (DoT stacks)",
            "Red altar: big slow CC-immune slime, splits into smalls when it dies",
            "Red buff Siphon Blood: heal absorb — stand next to a player to siphon it off",
            "Purple buff Stygian Infection: you drop void zones — keep them out of the raid",
            "Orange buff Exploding Infection: stagger the dispels, each one AoEs",
          },
          extraByDiff = {
            [15] = { "Heroic: soak the green Malignant Catalyst circles" },
          } },
        { label = "Sszorak",
          boss  = "Sszorak",
          title = "=== SSZORAK ===",
          lines = {
            "On pull, count the tornadoes in each third (1, 2, 3) — that is the Phase 2 wind order",
            "Apex Predator: taunt swap so each tank eats one Ravage and one Mutilate",
            "Ravage points AWAY from the raid, Mutilate points INTO the raid",
            "Tempest: dodge the tornadoes; Raging Crosswinds: pair with the player whose cone points at you",
            "Venomous Surge: drop the Cyst opposite the side the Phase 2 winds start from",
            "P2 Howling Maelstrom: assigned popper hits the Cyst as each wind starts, knocking the raid against it",
            "Dig In (~2 min): big damage-taken amp on the boss — burn every cooldown",
          },
          extraByDiff = {
            [15] = { "Heroic: split into two groups, each group soaks one Mutilate" },
          } },
        { label = "The Twin Fangs",
          boss  = "The Twin Fangs",
          title = "=== THE TWIN FANGS ===",
          lines = {
            "Eternal Venom kills you at max stacks — Ravenous Feast is the only way to shed them",
            "Vexhul: soak Caustic Globule orbs (+1 stack), dodge Stir the Depths waves (+1 stack)",
            "Kill Venomous Emergence adds fast — they pile stacks on the raid",
            "Ithraz Ravenous Feast: group soak removes stacks — go in whenever you are climbing",
            "Coiling Ichor: run to the room edge before it expires so the pool lands out of the way",
            "Stone Breaker (tank): remember the order the three soaks appeared and stand in them in that order",
            "P2 Submerge: watch the orb ring in the middle and dodge the beam that tracks it",
          },
          extraByDiff = {
            [15] = { "Heroic: three soak groups, one per Ravenous Feast circle; stack cap is lower — watch it" },
          } },
        { label = "The Coiled Altar",
          boss  = "The Coiled Altar",
          title = "=== THE COILED ALTAR ===",
          lines = {
            "P1 Zul'jan: assigned collectors carry Coalesced Venom to the drop point; tank aims Sever at the orbs there",
            "Guillotine: stack the group soak, then run out",
            "P2 Malacrass Dreadmarch: mind-controlled players walk UNDER the boss to be freed",
            "Manifestation of Dread: LOOK AT the ghost to freeze it, look away to move it to the drop point",
            "Soul Sever (tank) and Gloombomb: collect every clone or you die — spread for Gloombomb",
            "Intermission: Zul'jan takes double damage during Ghastly Regeneration; step on Malacrass fragments, but not too many at once",
            "P3: both phases run at once, and Soulbound means BOTH bosses must die together or the survivor gains 500% damage",
            "Lust in Phase 3",
          },
          extraByDiff = {
            [15] = {
              "Heroic: each collected Coalesced Venom adds a raid DoT stack when it explodes",
              "Heroic: two soak groups alternate Guillotine; focus and interrupt the Spiritcackle adds",
            },
          } },
        { label = "Ula'tek",
          boss  = "Ula'tek",
          title = "=== ULA'TEK ===",
          lines = {
            "Eggs: pick them up and break them — stand in Spectral Coils or DPS the egg to 0 for a WEAKENED add",
            "An egg that touches venom or finishes its cast hatches EMPOWERED — never let that happen",
            "P1: one tank on the head, one on the tail; swap during Caustic Waves",
            "Caustic Waves: watch Ula'tek's wings — waves come from boss AND tail",
            "Spectral Coils: soak on both sides of the tail; Call of the Serpent spawns more eggs",
            "Rage of the Shackled: burn Ula'tek's Heart, it takes double damage",
            "P2: split sides for the Doomscale Wardens, gather every small egg plus the Doomscale Egg, dump all into the Doomscale Cauldron",
            "P3: soak Serpent's Bite circles, stand where there are NO orbs for Caustic Waves, spread 5y for Volatile Purge, leave the platform on Circling Prey",
            "Lust in Phase 3",
          },
          extraByDiff = {
            [15] = {
              "Heroic: weakened adds stack Poisonous Bite; empowered adds apply Petrifying Sting (AoE DoT + heal absorb)",
              "Heroic: split Spectral Coils into two groups for the Soul Constrictor debuff",
            },
          } },
        { label = "Tips",
          title = "=== VENOMOUS ABYSS TIPS ===",
          lines = {
            "Route: Nek'zali, then two wings of two bosses, then Twin Fangs, Coiled Altar and Ula'tek from the central pit",
            "Tier: Sentinels hands, Lost Explorers shoulders, Vashnik chest, Sszorak legs, Twin Fangs helm",
            "Entrance: Vaults of Atal'Utek on The Coiled Isle — /way #2509 47.2 21.7",
            "Mythic Coiled Altar and Ula'tek drop 344 (Myth 9/6)",
          } },
      },
    },

    ------------------------------------------------------------------
    -- The Tidebound Grotto (1 boss lair, patch 12.1) — Mythic flex
    ------------------------------------------------------------------
    {
      name = "The Tidebound Grotto",
      tab  = "TG",
      tier = "Midnight S2 lair (12.1)",
      sections = {
        { label = "Nymrissa Wavecaller",
          boss  = "Nymrissa Wavecaller",
          title = "=== NYMRISSA WAVECALLER ===",
          lines = {
            "One mechanic cycle repeats all fight — no phases",
            "Kill the Bubblefin Murlocs before they reach the bubble",
            "Chilling Frost: if targeted, walk slowly in one spot so your orbs clump together",
            "Water Jet: tanks point the frontal away from the raid",
            "Swirling Whirlpools: stand in the section with NO whirlpool — they drift into the center",
            "Lust on pull",
          },
          extraByDiff = {
            [15] = { "Heroic: soak Frost Orb before it explodes, but not several at once (DoT stacks)" },
          } },
        { label = "Tips",
          title = "=== TIDEBOUND GROTTO TIPS ===",
          lines = {
            "Entrance: swim down at /way #2512 59.9 66.3 on The Coiled Isle",
            "Queues like a Delve: World difficulty solo-queue up to 40, premade Normal/Heroic 30, Mythic flex 25",
            "Only Season 2 boss with flexible Mythic, and it fills the Raid row of the Great Vault",
            "No tier tokens — item level tracks the first Venomous Abyss boss",
          } },
      },
    },

    ------------------------------------------------------------------
    -- The Voidspire (6 bosses) — tier tokens on bosses 2–5
    ------------------------------------------------------------------
    {
      name = "The Voidspire",
      tab  = "VS",
      tier = "Midnight",
      sections = {
        { label = "Interrupts/Dispels",
          title = "=== VOIDSPIRE - INT/DISP ===",
          lines = {
            "INTERRUPT: Pitch Bulwark (Shadowguard Stalwart/Annihilator), Voidbolt (Voidorbs)",
            "DISPEL: Void Marked on Averzian adds (Mythic Cosmic Shell stacks)",
          } },
        { label = "Imperator Averzian",
          boss  = "Imperator Averzian",
          title = "=== IMPERATOR AVERZIAN ===",
          lines = {
            "Tic-tac-toe grid — never let Averzian claim 3 adjacent tiles (March of the Endless = wipe)",
            "Soak Umbral Collapse on Voidshapers — 2 soaks per wave kill 2 adds; 1 tile still claims",
            "Kill Abyssal Voidshaper before Gathering Darkness or it becomes Obsidian Endwalker",
            "Keep boss 10y from claimed tiles (Imperator's Glory = 99% DR) and away from adds on Heroic+",
            "Tank swap Blackening Wounds around 8 stacks",
          } },
        { label = "Vorasius",
          boss  = "Vorasius",
          title = "=== VORASIUS ===",
          lines = {
            "Shadowclaw Slam spawns Void Crystals — walls block the room",
            "Kill Blistercreeps away from other dead creeps; death Blisterburst breaks crystal walls",
            "Break walls BEFORE Void Breath sweeps the room or melee stack for Primordial Roar",
            "Stay in melee range to avoid Primordial Roar raid-wide punishment",
          } },
        { label = "Fallen-King Salhadaar",
          boss  = "Fallen-King Salhadaar",
          title = "=== FALLEN-KING SALHADAAR ===",
          lines = {
            "Boss passively gains energy — at 100% he casts Entropic Unraveling (burn window)",
            "Concentrated Void orbs drift to boss — soak/kill before Void Infusion buffs him",
            "Stagger orb kills; interrupt and CC adds during Entropic Unraveling",
            "Push damage during Entropic Unraveling while managing orb paths",
          } },
        { label = "Vaelgor & Ezzorak",
          boss  = "Vaelgor & Ezzorak",
          title = "=== VAELGOR & EZZORAK ===",
          lines = {
            "Tank dragons 15y apart; swap when Vaelwing / Rakfang stacks hurt (2–3 stacks)",
            "Void Howl: stack tight so Voidorbs spawn grouped — grip/stun and interrupt Voidbolt",
            "Nullbeam spawns Nullzone — raid snaps tethers immediately; tank snaps LAST (raid DoT)",
            "Alternate Gloom orb soakers on Heroic; never back-to-back same player",
            "100 energy: stack in Radiant Barrier, kill Midnight Manifestation, spread Shadowmark rings",
          } },
        { label = "Lightblinded Vanguard",
          boss  = "Lightblinded Vanguard",
          title = "=== LIGHTBLINDED VANGUARD ===",
          lines = {
            "Council: Bellamy (Prot), Venel (Ret), Senn (Holy) — shared energy, rotating auras",
            "Focus Venel on pull (Avenging Wrath = takes extra damage); spread Avenger's Shield",
            "Mass Dispel Divine Shield after Bloodlust — bosses counter lust with Divine Shield",
            "Drag boss to room edge before 100 energy; break Senn Sacred Shield + interrupt Blinding Light",
            "Tank swap after Judgment — follow-up can kill off-tank",
          } },
        { label = "Crown of the Cosmos",
          boss  = "Crown of the Cosmos",
          title = "=== CROWN OF THE COSMOS ===",
          lines = {
            "P1: kill Undying Sentinels; aim Silverstrike Arrow to cleanse Void effects",
            "P2: grip adds into Silverstrike Ricochet path; swap Alleria and Rift Simulacrum at end",
            "P3: stack on Alleria; Aspect of the End tethers — break Ranged, then Melee, then Tank",
            "Gravity Collapse on tether break = 300% phys taken 12s — tanks swap around tank break",
            "Devouring Cosmos covers platform — use Dark Rush feathers to next slice; lust in P3",
          } },
        { label = "Tips",
          title = "=== VOIDSPIRE TIPS ===",
          lines = {
            "Tier tokens: Vorasius hands, Salhadaar shoulders, Vaelgor legs, Vanguard helm",
            "Wings unlock staggered — confirm your group's LFR wing before raid night",
          } },
      },
    },

    ------------------------------------------------------------------
    -- The Dreamrift (1 boss)
    ------------------------------------------------------------------
    {
      name = "The Dreamrift",
      tab  = "DR",
      tier = "Midnight",
      sections = {
        { label = "Chimaerus",
          boss  = "Chimaerus the Undreamt God",
          title = "=== CHIMAERUS ===",
          lines = {
            "Alndust Upheaval soak grants Alnsight — only way to see/damage Rift adds",
            "Rotate soak roster — without Alnsight you cannot kill adds; Rift Vulnerability stacks hurt",
            "Kill adds before they reach boss (Cannibalized Essence = +50% boss damage, stacks)",
            "100 energy: boss flies — dodge Corrupted Devastation, kill adds before Ravenous Dive",
            "Mythic: Dissonance splits realms (stay in assigned group); Rift Madness needs upstairs rescue",
          } },
        { label = "Tips",
          title = "=== DREAMRIFT TIPS ===",
          lines = {
            "Single-boss raid — no tier tokens; good early-season gear/checkpoint",
            "Roots/slows help control add movement toward Insatiable boss",
          } },
      },
    },

    ------------------------------------------------------------------
    -- March on Quel'Danas (2 bosses)
    ------------------------------------------------------------------
    {
      name = "March on Quel'Danas",
      tab  = "MQD",
      tier = "Midnight",
      sections = {
        { label = "Interrupts/Dispels",
          title = "=== QUEL'DANAS - INT/DISP ===",
          lines = {
            "INTERRUPT: Light Blast / Void Blast (Ember adds — matching feather only)",
            "INTERRUPT: Safeguard Prism channels on L'ura (33% DR each active Safeguard)",
            "CC Safeguard Prism with stuns/displacement when interrupts are on cooldown",
          } },
        { label = "Belo'ren",
          boss  = "Belo'ren, Child of Al'ar",
          title = "=== BELO'REN ===",
          lines = {
            "Voidlight Convergence assigns Light Feather or Void Feather — soak YOUR color only",
            "Light Dive / Void Dive: matching players soak; leaves pools + spawns Embers of Belo'ren",
            "Interrupt Light Eruption / Void Eruption on Embers; kill egg or Rebirth (likely wipe)",
            "Guardian's Edict: matching-color tank soaks frontal or boss gains 30% damage 30s",
            "Egg phase at 0% — real HP bar; Ashen Benediction -10% healing forever each cycle",
          } },
        { label = "Midnight Falls",
          boss  = "Midnight Falls",
          title = "=== MIDNIGHT FALLS (L'URA) ===",
          lines = {
            "P1: Death's Dirge memory game — learn Dark Rune order; heal Dusk Crystals into Dawn Crystals",
            "Interrupt/CC Safeguard Prism; kill crystal spawn adds before Terminate finishes",
            "Intermission: Galvanize beams to markers hit Void Cores — 4 cores cancel Cosmic Fission pull",
            "P3: Dawn Crystal carriers use Dawnlight Barrier vs The Dark Archangel — stack in blue ring",
            "Tank swap Heaven's Lance; avoid Cosmic damage while holding crystals (spawns soak pools)",
          } },
        { label = "Tips",
          title = "=== QUEL'DANAS TIPS ===",
          lines = {
            "Belo'ren teaches Light/Void polarity before the L'ura finale",
            "Hero on pull — Midnight Falls is on a fixed timer; push damage in P1",
          } },
      },
    },

    ------------------------------------------------------------------
    -- Sporefall (1 boss, patch 12.0.7) — Mythic flex 15–25
    ------------------------------------------------------------------
    {
      name = "Sporefall",
      tab  = "SF",
      tier = "Midnight (12.0.7)",
      sections = {
        { label = "Interrupts/Dispels",
          title = "=== SPOREFALL - INT/DISP ===",
          lines = {
            "INTERRUPT: Poison Burst (Sporecap — Heroic+)",
          },
          extraByDiff = {
            [14] = { "Normal: no Sporecap — focus Shroomling packs from Awaken Fungi only" },
            [15] = { "Heroic+: interrupt every Poison Burst on Sporecap" },
            [16] = { "Mythic: interrupt Poison Burst; Cross Fertilization needs 10y corpse split" },
          } },
        { label = "Rotmire",
          boss  = "Rotmire",
          title = "=== ROTMIRE ===",
          lines = {
            "Kill ALL adds before Fungal Bloom — living adds get Fungal Frenzy (heal + immune)",
            "Fungal Bloom: raid hit + 16s DoT + knockback; dead adds become Bursting Shroom — kill fast",
            "Festering Vines targets: move to EDGE before expire (Writhing Vines puddles)",
            "Tank swap every Putrid Fist (phys vulnerability)",
            "Rotting Pustules stacks ramp — clean early Fungal Bloom or healing falls behind",
          },
          extraByDiff = {
            [15] = {
              "Heroic: Sporecap (blue circle) — tank boss to it, interrupt Poison Burst, kill after adds",
              "Stack add corpses for easy Bursting Shroom AoE after Fungal Bloom",
            },
            [16] = {
              "Mythic Cross Fertilization: Shroomling and Fungling corpses must stay 10y apart",
              "Two kill piles — split raid; overlapping corpses spawn Bursting Doom Shroom (wipe)",
              "Mythic flex 15–25 players — health/adds scale with group size",
            },
          } },
        { label = "Tips",
          title = "=== SPOREFALL TIPS ===",
          lines = {
            "Single-boss raid (patch 12.0.7) — Sporefused gear, no tier tokens",
            "Plan healer CDs on each Fungal Bloom; one Bursting Shroom is survivable, two+ usually wipe",
          } },
      },
    },

    ------------------------------------------------------------------
    -- Outdoor world bosses (EJ lists these under "Midnight")
    ------------------------------------------------------------------
    {
      name = "World Bosses",
      tab  = "WB",
      tier = "Midnight outdoor",
      sections = {
        { label = "Lu'ashal",
          boss  = "Lu'ashal",
          title = "=== LU'ASHAL ===",
          lines = {
            "Eversong Woods weekly world boss — Champion-track loot",
            "Stack for raid CDs; treat as a short outdoor burn",
          } },
        { label = "Cragpine",
          boss  = "Cragpine",
          title = "=== CRAGPINE ===",
          lines = {
            "Weekly world boss (Zul'Aman / Eversong area) — Champion-track loot",
            "Watch ground effects; burn and loot, one kill per week per character",
          } },
        { label = "Thorm'belan",
          boss  = "Thorm'belan",
          title = "=== THORM'BELAN ===",
          lines = {
            "Harandar weekly world boss — Champion-track loot",
            "Lightbloom-afflicted beast; stack defensives on big hits",
          } },
        { label = "Predaxas",
          boss  = "Predaxas",
          title = "=== PREDAXAS ===",
          lines = {
            "Voidstorm weekly world boss — Champion-track loot",
            "Void-themed outdoor burn; one active world boss per week",
          } },
        { label = "Tips",
          title = "=== WORLD BOSS TIPS ===",
          lines = {
            "Only one Midnight world boss is up each week (skull WQ on map)",
            "EJ lists them under instance \"Midnight\" (id 1312) — not a raid lockout",
          } },
      },
    },
  },
}
